# Generated by Django 5.0.4 on 2024-05-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0002_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='pp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
