# Generated by Django 5.0.4 on 2024-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BigApp', '0003_logindb_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindb',
            name='cpassword',
        ),
        migrations.AddField(
            model_name='logindb',
            name='Confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
